---
- name: Setup and Deploy Tomcat Container locally
  hosts: localhost
  connection: local

  tasks:
    - name: Pull Tomcat image from Docker Hub using Podman
      containers.podman.podman_image:
        name: tomcat:latest

    - name: List Podman images
      ansible.builtin.command:
        cmd: podman images
      register: images_output

    - name: Display Podman images
      ansible.builtin.debug:
        var: images_output.stdout_lines
