---
- name: Setup and Deploy Tomcat Container locally
  hosts: localhost
  connection: local

  tasks:
    - name: Pull Tomcat image from Docker Hub using Podman
      containers.podman.podman_image:
        name: tomcat:latest
        executable: /usr/bin/podman  # Specify the correct path to podman executable

    - name: List Podman images
      ansible.builtin.command:
        cmd: /usr/bin/podman images  # Specify the correct path to podman executable
      register: images_output

    - name: Display Podman images
      ansible.builtin.debug:
        var: images_output.stdout_lines
