---
- name: Test Connection with Semaphore Container
  hosts: localhost
  connection: local

  tasks:
    - name: Create a test file on local /tmp
      file:
        path: /tmp/semaphore_test_file.txt
        state: touch

    - name: Write a message to the test file
      copy:
        dest: /tmp/semaphore_test_file.txt
        content: "Semaphore connection test successful!"
