---
- name: Setup and Deploy Tomcat Container on VM
  hosts: my_vms
    #become: yes
  tasks:
    - name: Pull Tomcat image from Docker Hub
      containers.podman.podman_image:
        name: tomcat:latest

    - name: List Podman images
      ansible.builtin.command:
        cmd: podman images
      register: images_output

    - name: Display Podman images
      ansible.builtin.debug:
        var: images_output.stdout_lines
