---
- name: Deploy Tomcat container
  hosts: my_servers 
  vars:
    ansible_python_interpreter: /usr/bin/python3
    tomcat_image: "docker.io/library/tomcat:latest"
    tomcat_container_name: "tomcat1"
    tomcat_ports:
      - "8075:8080"
    tomcat_status_filter: "name=tomcat_container"
    war_file: "/home/madhur/test/webapps/SampleWebApp.war"  # Update this with the path to your WAR file
    tomcat_webapps_dir: "/usr/local/tomcat/webapps"

  tasks:
    - name: Pull the Tomcat container image
      containers.podman.podman_image:
        name: "{{ tomcat_image }}"
        tag: latest

    - name: Run Tomcat container
      containers.podman.podman_container:
        name: "{{ tomcat_container_name }}"
        image: "{{ tomcat_image }}"
        state: started
        ports: "{{ tomcat_ports }}"
        volumes:
          - "{{ war_file }}:/usr/local/tomcat/webapps/ROOT.war:Z"  # Mount WAR file as ROOT.war

    - name: Wait for Tomcat to start
      wait_for:
        host: localhost
        port: 8075
        delay: 10
        timeout: 120

    - name: Verify Tomcat container is running
      command: podman ps --filter "{{ tomcat_status_filter }}" --format "{% raw %}{{.Status}}{% endraw %}}"
      register: container_status

    - name: Debug container status
      debug:
        var: container_status.stdout

    - name: Print Tomcat container logs for debugging
      command: podman logs {{ tomcat_container_name }}
      register: tomcat_logs
      ignore_errors: yes

    - name: Debug Tomcat logs
      debug:
        var: tomcat_logs.stdout

    - name: Copy WAR file to Tomcat container
      copy:
        src: "{{ war_file }}"
        dest: "{{ tomcat_container_name }}:/usr/local/tomcat/webapps/ROOT.war"          # {{ tomcat_webapps_dir }}/ROOT.war"

    - name: Restart Tomcat container to deploy WAR
      containers.podman.podman_container:
        name: "{{ tomcat_container_name }}"
        image: "{{ tomcat_image }}"
        state: started
        restart: true

    - name: Wait for Tomcat to restart
      wait_for:
        host: localhost
        port: 8075
        delay: 10
        timeout: 120

    - name: Verify Tomcat container is running after restart
      command: podman ps --filter "{{ tomcat_status_filter }}" --format "{% raw %}{{.Status}}{% endraw %}}"
      register: container_status_after_restart

    - name: Debug container status after restart
      debug:
        var: container_status_after_restart.stdout

    - name: Print Tomcat container logs after restart for debugging
      command: podman logs {{ tomcat_container_name }}
      register: tomcat_logs_after_restart
      ignore_errors: yes

    - name: Debug Tomcat logs after restart
      debug:
        var: tomcat_logs_after_restart.stdout
