- hosts: localhost
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      tags: install

    - name: Configure nginx
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      tags: configure

    - name: Start nginx
      service:
        name: nginx
        state: started
      tags: start
